/**
 * i18n.mjs — report language dictionary (en / zh).
 *
 * Single source of truth for all user-visible copy that is NOT generated by the
 * LLM agents (chapter scaffolding, score-table labels, degraded banner, chart
 * source prefix, disclaimer). Agent-produced prose follows the report `lang`
 * via the agent contracts; this module covers the deterministic UI strings.
 *
 * Default language is "en" (English). Pass `lang: "zh"` for Chinese reports.
 *
 * Usage:
 *   import { t, DEFAULT_LANG, SUPPORTED_LANGS } from "./lib/i18n.mjs";
 *   t("chartSourceLabel", "en")   // → "Source: "
 *   t("chartSourceLabel", "zh")   // → "数据来源："
 *   t("chartSourceLabel")         // → "Source: " (default en)
 */

export const DEFAULT_LANG = "en";
export const SUPPORTED_LANGS = Object.freeze(["en", "zh"]);

const DICT = {
  // ── chart SVG source-note prefix (render_product_svg.mjs) ──
  chartSourceLabel: { en: "Source: ", zh: "数据来源：" },

  // ── build-pdf.mjs chapter scaffolding ──
  htmlLang:          { en: "en", zh: "zh" },
  keyInsightsTitle:  { en: "KEY INSIGHTS", zh: "KEY INSIGHTS" },
  summaryTitle:      { en: "Summary", zh: "本期摘要" },
  reportHeader:      { en: "Key Insights", zh: "报告要点" },
  expertView:        { en: "Expert Views", zh: "专家观点" },
  riskMonitor:       { en: "Risk Monitor", zh: "风险监控" },
  riskPolicy:        { en: "▼ Policy Risk", zh: "▼ 政策风险" },
  riskGeopolitics:   { en: "▼ Geopolitical Risk", zh: "▼ 地缘风险" },
  riskSupplyDemand:  { en: "● Supply-Demand Risk", zh: "● 供需风险" },
  riskHeader:        { en: "Risk Alerts", zh: "三、风险提示" },
  riskBoxTitle:      { en: "⚠ Key Risk Factors", zh: "⚠ 主要风险因子" },
  macroOverviewH2:   { en: "I. Global Macro Overview", zh: "一、全球宏观概览" },
  commoditiesH2:     { en: "II. Commodity Markets", zh: "二、大宗商品市场追踪" },
  commoditiesPlaceholder: { en: "(Commodity data to be filled)", zh: "（大宗商品数据待填入）" },
  adviceH2:          { en: "IV. AI Rating & Investment View", zh: "四、AI评级与投资建议" },

  // ── default keyPoints / risks fallback (build-pdf.mjs) ──
  defaultKeyPoints: {
    en: [
      "Global macro resilience persists; commodity demand support intact",
      "Divergence widens: uranium/copper supply-constrained, lithium/cobalt under pressure",
      "Geopolitical risk premium lifts energy prices; consider energy allocation",
    ],
    zh: [
      "本周宏观数据显示全球经济韧性持续，大宗商品需求支撑未明显减弱",
      "资源品种分化加剧：铀、铜供给约束持续，锂、钴市场承压",
      "地缘政治风险溢价推升能源价格，建议适当配置能源板块",
    ],
  },
  defaultRisks: {
    en: [
      "Fed policy pivot risk: rate path uncertainty remains high",
      "Geopolitical supply disruption: critical minerals supply chain vulnerability rising",
      "Commodity cycle reversal: some commodities have fully priced in gains",
    ],
    zh: [
      "美联储政策转向风险：利率路径不确定性仍高",
      "地缘政治供应中断：关键矿产供应链脆弱性上升",
      "大宗商品周期反转：部分品种涨幅已充分定价",
    ],
  },

  // ── back-cover copy (build-pdf.mjs) ──
  endOfReport:    { en: "End of Report", zh: "End of Report · 报告完结" },
  aboutBody:      { en: "MiningClaw is an AI multi-factor mining-economy research platform.", zh: "MiningClaw 是基于 AI 多因子模型的矿业经济研究平台。" },
  coverageMacro:  { en: "Macro Research", zh: "宏观研究" },
  coverageComm:   { en: "Commodities", zh: "大宗商品" },
  coverageMining: { en: "Mining Investment", zh: "矿业投资" },
  frequencyBody:  { en: "Weekly / Monthly / Thematic", zh: "周报 / 月报 / 专题" },

  // ── disclaimer (build-pdf.mjs + render-with-watermark.mjs) ──
  disclaimerBody: {
    en: "This report is auto-generated by MiningClaw AI Intelligence Systems for institutional investors only. It does not constitute investment advice. All data sources are cited within each section. AI-generated.",
    zh: "本报告由 MiningClaw AI Intelligence Systems 自动生成，内容仅供机构投资者参考，不构成投资建议或要约。市场有风险，投资需谨慎。所有数据来源均已在报告各章节内标注。本报告由 AI 辅助生成，AI GENERATED。",
  },

  // ── degraded score table (render-with-watermark.mjs) ──
  scoreTableHeader:  { en: "Internal Audit Score Detail (dim ≥ 9.5 = pass)", zh: "内审评分明细 (单项 ≥ 9.5 为达标)" },
  scoreColDim:       { en: "Dimension", zh: "维度" },
  scoreColMech:      { en: "Mech", zh: "机械分" },
  scoreColLlm:       { en: "LLM", zh: "LLM 分" },
  scoreColFused:     { en: "Fused", zh: "融合分" },
  scoreColStatus:    { en: "Status", zh: "状态" },
  scorePass:         { en: "✓ Pass", zh: "✓ 达标" },
  scoreFail:         { en: "✗ Below 9.5", zh: "✗ 未达 9.5" },
  scoreDimNames: {
    en: {
      event_coverage: "Event Coverage", analytical_depth: "Analytical Depth",
      geopolitical_rigor: "Geopolitical Rigor", data_integrity: "Data Integrity",
      structure_compliance: "Structure Compliance", language_quality: "Language Quality",
    },
    zh: {
      event_coverage: "事件覆盖 Event Coverage", analytical_depth: "分析深度 Analytical Depth",
      geopolitical_rigor: "地缘严谨 Geopolitical Rigor", data_integrity: "数据完整性 Data Integrity",
      structure_compliance: "版式合规 Structure Compliance", language_quality: "语言质量 Language Quality",
    },
  },

  // ── degraded cover banner (enforce-gate.mjs) ──
  degradedBanner: {
    en: "Weighted total below 9.0 internal threshold — internal discussion only, do not distribute externally",
    zh: "本报告加权总分未达 9.0 内审阈值, 仅供内部讨论, 不得对外",
  },
};

/**
 * Look up a localized string.
 *
 * Fails closed on an unsupported lang (throws), consistent with validateLang().
 * An earlier version silently fell back to DEFAULT_LANG via `??` — that masked
 * typos like `lang: "eng"` rendering the whole report in the wrong language
 * instead of failing loudly. validateLang() at the CLI boundary is the primary
 * guard; t() throwing is the belt-and-suspenders for in-pipeline callers.
 *
 * @param {string} key - dictionary key (see DICT above)
 * @param {string} [lang] - "en" | "zh"; defaults to DEFAULT_LANG
 * @returns {string|string[]} the localized value (string for most keys, array for default*)
 * @throws {Error} if key is unknown or lang is not in SUPPORTED_LANGS
 */
export function t(key, lang = DEFAULT_LANG) {
  const entry = DICT[key];
  if (!entry) throw new Error(`i18n: unknown key "${key}"`);
  if (!SUPPORTED_LANGS.includes(lang)) {
    throw new Error(`i18n: unsupported lang "${lang}" (supported: ${SUPPORTED_LANGS.join(", ")})`);
  }
  const val = entry[lang];
  if (val === undefined) {
    throw new Error(`i18n: key "${key}" has no "${lang}" translation`);
  }
  return val;
}

/**
 * Validate a lang code; throw on unsupported value (fail-closed).
 * @param {string} lang
 * @returns {string} the validated lang (or DEFAULT_LANG if nullish)
 */
export function validateLang(lang) {
  if (lang == null) return DEFAULT_LANG;
  if (!SUPPORTED_LANGS.includes(lang)) {
    throw new Error(`i18n: unsupported lang "${lang}" (supported: ${SUPPORTED_LANGS.join(", ")})`);
  }
  return lang;
}
